<a href="https://colab.research.google.com/github/SumbulSultan/TTA/blob/main/HMLTWK3NPSumbulSultan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
#Task 1

a = np.arange(9)
print("Array from 0 to 9:")
print(a)

In [ ]:
#Task 2 
b = np.ones((3,3),dtype=bool)
print(b)

In [ ]:
#Task 3 
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.where(c%2 == 0)
print(d)

In [ ]:
#Task 4
e = np.array([1,2,3,4,5,6,7,8,9,10])
f = e%2 ==1 
e[f] = -1
print(e)

In [ ]:
#Task 5
g = np.array([1,2,3,4,5,6,7,8,])
print(g)
h = g.reshape(2,4)
print(h)

In [10]:
#Task 6 
i = np.arange(1,10).reshape(3,3)
print(i)
j = np.arange(10,19).reshape(3,3)
print(j)
k = np.dot(i,j)
print(k)
l = np.sum(k,axis = 1)
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]
